---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.applicationName }}
spec:
  port:
    targetPort: web
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.applicationName }}
    weight: 100
  wildcardPolicy: None
