---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customers-pvc
  namespace: {{ .Values.cicdNamespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pipelineStorage.pvcSize }}
  {{- if .Values.pipelineStorage.storageClassName }}
  storageClassName: {{ .Values.pipelineStorage.storageClassName }}
  {{- end }}
