---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-view-{{ .Values.namespacePermissions.user }}
  namespace: {{ .Values.demoNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: default
  namespace: "{{ .Values.demoNamespace }}"
