---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-secret
  namespace: {{ .Values.cicdNamespace }}
  annotations:
    tekton.dev/git-0: {{ .Values.repo.url }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.repo.user }}
  password: {{ .Values.repo.password }}
