---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-with-subdir
  namespace: {{ .Values.cicdNamespace }}
spec:
  description: >-
    This Task can be used to run a Maven build in a specified subdirectory.
  workspaces:
  - name: source
  params:
  - name: GOALS
    description: maven goals to run
    type: array
    default:
    - "package"
  - name: subdirectory
    description: Subdirectory in which the maven goals will be run.
    type: string
    default: ""

  steps:
  - name: mvn-goals
    image: maven:3.6-openjdk-11
    workingDir: $(workspaces.source.path)/$(params.subdirectory)
    command: ["/usr/bin/mvn"]
    args:
      - -Dmaven.repo.local=$(workspaces.source.path)/.m2
      - "$(params.GOALS)"
