version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: changeme
      MONGO_INITDB_ROOT_PASSWORD: changeme
      MONGO_INITDB_DATABASE: todolist
    ports:
        - 27017:27017
        - 9229:9229
    volumes:
        - ./mongo-init:/docker-entrypoint-initdb.d/:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: changeme
      ME_CONFIG_MONGODB_ADMINPASSWORD: changeme
      ME_CONFIG_MONGODB_URL: mongodb://changeme:changeme@mongo:27017/

  todolist:
    build:
      context: .
      dockerfile: Dockerfile
    image: localhost/todolist:latest
    restart: always
    ports:
      - 8000:8000
    environment:
      clientOptions: mongodb://changeme:changeme@mongo:27017/todolist
