---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customers-tomcat-gitops
  namespace: retail-{{ .Values.user }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-{{ .Values.user }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
  source:
    repoURL: http://gitea.gitea.svc:3000/{{ .Values.user }}/modern-app-dev.git
    targetRevision: main
    path: helm/customers-tomcat-gitops
    helm:
      values: |
        customerDatabase:
          hostname: {{ .Values.customerDatabase.hostname }}
          user: {{ .Values.customerDatabase.user }}
          password: {{ .Values.customerDatabase.password }}
        image:
          registry: image-registry.openshift-image-registry.svc:5000
          account: retail-{{ .Values.user }}
          repository: customers-tomcat-gitops
