spring:
  datasource:
    url: jdbc:postgresql://postgresql-orders:5432/orders
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      jdbc:
        lob:
          non_contextual_creation: true

opentracing:
  jaeger:
    http-sender:
      url: http://jaeger-all-in-one-inmemory-collector:14268/api/traces
