apiVersion: noobaa.io/v1alpha1
kind: NooBaa
metadata:
  name: noobaa
  namespace: openshift-storage
spec:
 dbResources:
   requests:
     cpu: "0.5"
     memory: 1Gi
 coreResources:
   requests:
     cpu: "0.5"
     memory: 1Gi
