services:
  orders:
    url: http://{{ .Values.ordersHost }}:8080/orders
  inventory:
    url: http://{{ .Values.inventoryHost }}:8080/products
  customers:
    url: http://{{ .Values.customersHost }}:8080/{{ .Values.customersApp }}/customers

hystrix:
  command:
    ProductsCall:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
  threadpool:
    ProductsThreads:
      coreSize: 20
      maxQueueSize: 200
      queueSizeRejectionThreshold: 200

opentracing:
  jaeger:
    http-sender:
      url: http://jaeger-all-in-one-inmemory-collector:14268/api/traces
  spring:
    cloud:
      jdbc:
        enabled: false
      feign:
        enabled: false
      jms:
        enabled: false
      zuul:
        enabled: false
      websocket:
        enabled: false
      hystrix:
        strategy:
          enabled: true
      async:
        enabled: false
