---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.applicationName }}-secret
type: Opaque
data:
{{- range $path, $bytes := .Files.Glob "secret/*" }}
{{ base $path | indent 2 }}: {{ tpl ($.Files.Get $path) $ | b64enc }}
{{ end }}
