#!/bin/sh

OCP_IMAGE_GROUP=dgrigore
OCP_IMAGE_NAME=bm-amq-consumer
OCP_IMAGE_VERSION=stable

OCP_REGISTRY=quay.io
set -eu

# New app
oc new-app $OCP_REGISTRY/$OCP_IMAGE_GROUP/$OCP_IMAGE_NAME:$OCP_IMAGE_VERSION \
	ACTIVEMQ_SERVICE_PROTOCOL=tcp \
	ACTIVEMQ_SERVICE_HOST=amq-broker-ssl-amq-tcp.amq-core.svc.cluster.local \
	ACTIVEMQ_SERVICE_PORT=61616 \
	ACTIVEMQ_BROKER_USERNAME=admin \
	ACTIVEMQ_BROKER_PASSWORD=p4ss \
	CONSUMERS=2 \
	JAVA_MAX_MEM_RATIO=75 \
	MAX_CONNECTIONS=50 \
	PERFORMANCE_QUEUE_ONE=amq-performance.inbox \
	PRODUCERS=2
