apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.applicationName }}-config
data:
{{- range $path, $bytes := .Files.Glob "config/*" }}
{{ base $path | indent 2 }}: |
{{ tpl ($.Files.Get $path) $ | indent 4 }}
{{ end }}
