on:
  push:
    paths:
      - "apps/todolist-mariadb-go"
      - .github/workflows/todolist-mariadb-go.yaml
  pull_request:
jobs:
  build-push-docker:
    env:
      REGISTRY: "ghcr.io/konveyor"
    name: build-push-docker
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    # In this step, this action saves a list of existing images,
    # the cache is created without them in the post run.
    # It also restores the cache if it exists.
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
    - name: Setup Docker buildx
      id: buildx
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
    - name: "Build and push docker image"
      uses: actions/checkout@v2
    - name: "Build and push docker image"
      run: |
        cd apps/todolist-mariadb-go
        REGISTRY=$REGISTRY make manifest-docker
